import type { Metadata } from "next";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import localFont from "next/font/local";
import "./globals.css";

const myAspekta = localFont({
  src: [
    {
      path: "./fonts/Aspekta/Aspekta-400.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Aspekta/Aspekta-450.ttf",
      weight: "450",
      style: "normal",
    },
    {
      path: "./fonts/Aspekta/Aspekta-600.ttf",
      weight: "600",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myAspekta.className} flex-1 flex-col`}>
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
